### PR TITLE
Human friendly

### PR DESCRIPTION
**Pull request by makotom**
* Added human-friendly explanation on documentations
* Added human-friendly error messages
* Enhanced tests to become human-friendly (now it covers 100 % of the server codes)

**Important note**: This will remove old `/i` endpoint, which was left behind for backward compatibility. This sounds human-unfriendly, but actually it IS human-friendly - no end user expects that `/i` returns unusable JSON instead of `config.yml`. This change should not affect the latest code bases, and developers still relying on old code bases are strongly encouraged to update themselves.

### CODE REVIEW

**Comment by makotom** [comment]
Two notes:

* Once `20200511-executor` is merged into `dev`, this PR should be rebased to `dev`. i.e. Maybe there is a need for attention upon merge.
* I expect https://github.com/heug/jenkinsfile-circleci/pull/19/commits/7c9c8c1eb53b32fb1d8b359e19f467656c88740a effectively closes #17.

**Comment by heug** [comment]
this looks great! wondering if having `jenkinsto.cc/i`respond with `JenkinsToCCIResponder.convertJenkinsfileToConfigYml` could be good "branding", since our shorthand for CircleCI is "CCI"...

**Comment by makotom** [comment]
@heug Good point, and I revived `/i` endpoint with `JenkinsToCCIResponder.convertJenkinsfileToConfigYml`!
(Originally I was thinking of reserving `/i` for Web UI, but I realized that the Web UI can use `GET /i` while API calls use `POST /i` - this was the main rationality to revive the endpoint.)

**Comment by heug** [comment]
🎉

**Pull request merged**
